package(default_visibility = ["//visibility:public"], licenses = ["reciprocal"])
load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
  name = "ffe",
  srcs = ["ffe.go"],
  deps = ["//github.com/honr/vulcan/static:go_default_library"],
)
