package(default_visibility = ["//visibility:public"])
load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
  name = "go_default_library",
  srcs = ["static.go"],
  deps = [
      "//github.com/honr/vulcan/htl:go_default_library",
  ],
)
